# # # # # # # # # # # # # # # #
#                             #
#     ==Customization==       #
#                             #
# # # # # # # # # # # # # # # #

# Font
font_family      Mono
font_size        10.0
# Background
background #141414

# Sound effect
enable_audio_bell no
# Beep duration
visual_bell_duration 0

# == Change Text Size While Running ==
map ctrl+shift+period change_font_size all +2.0
map ctrl+shift+comma change_font_size all -2.0

# # # # # # # # # # # # # # # #
#                             #
#       ==Shortcuts==         #
#                             #
# # # # # # # # # # # # # # # #

# == Pane Actions ==
# Launch a pane horizontally
map ctrl+shift+h launch --location=hsplit
# Launch a pane vertically
map ctrl+shift+j launch --location=vsplit
# Closes currently chosen pane
map ctrl+shift+q close_window

# Moving between panes
map ctrl+shift+left neighboring_window left
map ctrl+shift+right neighboring_window right
map ctrl+shift+up neighboring_window up
map ctrl+shift+down neighboring_window down

#Resize panes
map ctrl+alt+left resize_window narrower 5
map ctrl+alt+right resize_window wider 5
map ctrl+alt+up resize_window taller 5
map ctrl+alt+down resize_window shorter 5

# == Tab Actions ==
# Detach a tab into a new window
map ctrl+shift+d detach_tab
# Going to tab 1-10
map ctrl+shift+1 goto_tab 1
map ctrl+shift+2 goto_tab 2
map ctrl+shift+3 goto_tab 3
map ctrl+shift+4 goto_tab 4
map ctrl+shift+5 goto_tab 5
map ctrl+shift+6 goto_tab 6
map ctrl+shift+7 goto_tab 7
map ctrl+shift+8 goto_tab 8
map ctrl+shift+9 goto_tab 9
map ctrl+shift+0 goto_tab 10
# Moving between tabs
map shift+left previous_tab
map shift+right next_tab
#Scroll
map shift+up scroll_line_up
map shift+down scroll_line_down

# == Internal Actions ==
# Reloads config file live
map ctrl+shift+f1 load_config_file


